server:
  port: 3000

spring:
  application:
    name: chguburoapi
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    #          ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/chesuburo
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
##          ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

token:
  access: hhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdh
  refresh: kjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslk

#dirs:
#  templates: C:\Users\User\Documents\_PROJECTS\JAVA\chesuburoapi\src\main\resources\templates
#  uploads: C:\Users\User\Documents\_PROJECTS\JAVA\chesuburoapi\src\main\resources\uploads
#dirs:
#  templates: /app/resources/templates
#  uploads: /app/resources/uploads
dirs:
  templates: /Users/rozoomcool/Documents/_PROJECTS/backend/chesuburoapi/src/main/resources/templates
  uploads: /Users/rozoomcool/Documents/_PROJECTS/backend/chesuburoapi/src/main/resources/uploads