server:
  port: 3000

spring:
  application:
    name: chguburoapi

  datasource:
    url: jdbc:postgresql://localhost:5432/chesuburo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
#          ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  access: hhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdh
  refresh: kjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslk
